In [1]:
import pandas as pd
from src.detector import detect
from src.utils.metrics import bone_wise_metrics

In [2]:
df = pd.read_parquet("data/validation.parquet")

In [3]:
broken_cols = df.filter(regex="Broken").columns.tolist()
broken_labels = df[broken_cols].notna()

In [4]:
res = detect(df)
res

,BrokenHip,BrokenAb,BrokenChest,BrokenNeck,BrokenLShoulder,BrokenRShoulder,BrokenLUArm,BrokenRUArm,BrokenLFArm,BrokenRFArm,...,BrokenRHand,BrokenLThigh,BrokenRThigh,BrokenLShin,BrokenRShin,BrokenLFoot,BrokenRFoot,BrokenHead,broken,checkers
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24181,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,[GravityAlignmentChecker]
24182,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,[GravityAlignmentChecker]
24183,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,[GravityAlignmentChecker]
24184,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,[GravityAlignmentChecker]
24185,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,[GravityAlignmentChecker]

In [5]:
bone_wise_metrics(broken_labels, res, ['RHand', 'LHand', 'RFoot', 'LFoot'])

    bone  precision    recall        f1  support
0  RHand   0.824284  0.891147  0.856413     5264
1  LHand   0.863649  0.891975  0.877583     7165
2  RFoot   0.815422  0.909189  0.859756     1861
3  LFoot   0.706258  0.685254  0.695597      807