In [1]:
import pandas as pd
from src.detector import detect
from src.utils.metrics import bone_wise_metrics
from src.detector.checkers import AbsoluteLimitChecker, GravityAlignmentChecker

In [2]:
df = pd.read_parquet("data/validation.parquet")

In [3]:
broken_cols = df.filter(regex="Broken").columns.tolist()
broken_labels = df[broken_cols].notna()

In [4]:
res = detect(
    df,
    [
        AbsoluteLimitChecker(
            calibrate=True,
            tpose_window=500,
        ),
        GravityAlignmentChecker(
            bones=["RHand", "LHand"],
            threshold_cos=0.7,
            calibration_window=500,
            temporal_filter=True,
            temporal_required=35,
            temporal_window=40
        ),
    ],
)
res

,BrokenHip,BrokenAb,BrokenChest,BrokenNeck,BrokenLShoulder,BrokenRShoulder,BrokenLUArm,BrokenRUArm,BrokenLFArm,BrokenRFArm,...,BrokenRHand,BrokenLThigh,BrokenRThigh,BrokenLShin,BrokenRShin,BrokenLFoot,BrokenRFoot,BrokenHead,broken,checkers
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24181,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
24182,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
24183,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
24184,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
24185,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]

In [5]:
bone_wise_metrics(broken_labels, res, ['RHand', 'LHand', 'RFoot', 'LFoot'])

    bone  precision    recall        f1  support
0  RHand   0.938763  0.922033  0.930323     4938
1  LHand   0.929452  0.860705  0.893759     7179
2  RFoot   0.930711  0.850778  0.888951     1863
3  LFoot   0.883382  0.750000  0.811245      808