In [12]:
import pandas as pd
from src.detector import detect
from src.utils.metrics import bone_wise_metrics
from src.detector.checkers import AbsoluteLimitChecker, GravityAlignmentChecker

In [13]:
df = pd.read_parquet("data/validation.parquet")

In [14]:
broken_cols = df.filter(regex="Broken").columns.tolist()
broken_labels = df[broken_cols].notna()

In [15]:
res = detect(df, [AbsoluteLimitChecker(calibrate=False, tpose_window=1500, plot=False), GravityAlignmentChecker()])
res

,BrokenHip,BrokenAb,BrokenChest,BrokenNeck,BrokenLShoulder,BrokenRShoulder,BrokenLUArm,BrokenRUArm,BrokenLFArm,BrokenRFArm,...,BrokenRHand,BrokenLThigh,BrokenRThigh,BrokenLShin,BrokenRShin,BrokenLFoot,BrokenRFoot,BrokenHead,broken,checkers
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24181,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,[GravityAlignmentChecker]
24182,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,[GravityAlignmentChecker]
24183,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,[GravityAlignmentChecker]
24184,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,[GravityAlignmentChecker]
24185,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,[GravityAlignmentChecker]

In [16]:
bone_wise_metrics(broken_labels, res, ['RHand', 'LHand', 'RFoot', 'LFoot'])

    bone  precision    recall        f1  support
0  RHand   0.824561  0.892857  0.857351     5264
1  LHand   0.863753  0.896301  0.879726     7165
2  RFoot   0.813920  0.904890  0.856997     1861
3  LFoot   0.715711  0.711276  0.713487      807