In [6]:
import pandas as pd
from src.detector import detect
from src.skeletons.natnet_skeleton import NATNET
from src.utils.metrics import bone_wise_metrics
from src.detector.checkers import(
    AbsoluteLimitChecker,
    GravityAlignmentChecker,
    AngularVelocityChecker,
    LinearAccelerationChecker,
    AngularAccelerationChecker
)

In [7]:
df = pd.read_parquet("data/validation.parquet")

In [8]:
broken_cols = df.filter(regex="Broken").columns.tolist()
broken_labels = df[broken_cols].notna()

In [ ]:
bones = [
 'Hip',
 'Ab',
 'Chest',
 'Neck',
 'LShoulder',
 'RShoulder',
 'LUArm',
 'RUArm',
 'LFArm',
 'RFArm',
 'LHand',
 'RHand',
 'LThigh',
 'RThigh',
 'LShin',
 'RShin',
 'LFoot',
 'RFoot',
 'Head'
 ]

# bones = ["RFArm", "RUArm"]

res = detect(
    df,
    [
        AbsoluteLimitChecker(
            calibrate=True,
            plot=False,
            tpose_window=500,
            bones=bones
        ),
        GravityAlignmentChecker(
            bones=bones,
            threshold_cos=0.7,
            calibration_window=500,
            temporal_filter=False,
            temporal_required=35,
            temporal_window=40
        ),
        AngularVelocityChecker(
            threshold_rad_s=10.0,
            bones=bones,
            plot=False,
        ),
        LinearAccelerationChecker(
            bones=bones,
            plot=False,
        ),
        AngularAccelerationChecker(
            bones=bones,
            plot=False
        )
    ],
)
res

,BrokenHip,BrokenAb,BrokenChest,BrokenNeck,BrokenLShoulder,BrokenRShoulder,BrokenLUArm,BrokenRUArm,BrokenLFArm,BrokenRFArm,...,BrokenRHand,BrokenLThigh,BrokenRThigh,BrokenLShin,BrokenRShin,BrokenLFoot,BrokenRFoot,BrokenHead,broken,checkers
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24181,False,False,False,False,False,False,True,True,True,False,...,False,False,False,False,False,False,False,False,True,"[AbsoluteLimitChecker, GravityAlignmentChecker]"
24182,False,False,False,False,False,False,True,True,True,False,...,False,False,False,False,False,False,False,False,True,"[AbsoluteLimitChecker, GravityAlignmentChecker]"
24183,False,False,False,False,False,False,True,True,True,False,...,False,False,False,False,False,False,False,False,True,"[AbsoluteLimitChecker, GravityAlignmentChecker]"
24184,False,False,False,False,False,False,True,True,True,False,...,False,False,False,False,False,False,False,False,True,"[AbsoluteLimitChecker, GravityAlignmentChecker]"
24185,False,False,False,False,False,False,True,True,True,False,...,False,False,False,False,False,False,False,False,True,"[AbsoluteLimitChecker, GravityAlignmentChecker]"

In [10]:
# bone_wise_metrics(broken_labels, res, ['RHand', 'LHand', 'RFoot', 'LFoot'])
bone_wise_metrics(broken_labels, res, bones)

         bone  precision    recall        f1  support
0         Hip   0.000000  0.000000  0.000000        0
1          Ab   0.000000  0.000000  0.000000        0
2       Chest   0.000000  0.000000  0.000000        0
3        Neck   0.000000  0.000000  0.000000        0
4   LShoulder   0.003106  0.121951  0.006058      123
5   RShoulder   0.264901  1.000000  0.418848      280
6       LUArm   0.024650  0.386849  0.046347     1171
7       RUArm   0.090595  0.955300  0.165496     2170
8       LFArm   0.616775  0.389943  0.477804     4375
9       RFArm   0.655194  0.625261  0.639878     3349
10      LHand   0.885750  0.895250  0.890475     7179
11      RHand   0.878913  0.949575  0.912878     4938
12     LThigh   0.000000  0.000000  0.000000        0
13     RThigh   0.000000  0.000000  0.000000        0
14      LShin   0.000000  0.000000  0.000000        0
15      RShin   0.000000  0.000000  0.000000        0
16      LFoot   0.721739  0.821782  0.768519      808
17      RFoot   0.799814  0.922169  0.856644     1863
18       Head   0.464534  0.222667  0.301037     3000